# Generated by Django 4.1.7 on 2023-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.BooleanField(default=False),
        ),
    ]
