# Generated by Django 4.1.7 on 2023-08-31 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_dmessage_messageroom_delete_message_dmessage_room_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DMessage',
            new_name='Message',
        ),
    ]
