# Generated by Django 4.1.7 on 2023-08-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(default='Creative Poultry Business', max_length=100),
        ),
    ]
