# Generated by Django 4.1.7 on 2023-08-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Unit',
            new_name='unit',
        ),
    ]
