# Generated by Django 4.1.7 on 2023-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_unit_address_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('cashondelivery', 'cod')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
