# Generated by Django 4.1.7 on 2023-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_promocode_order_discount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
